# -*- mode: python -*-
# 

import wafutils

def build( bld ):
    syslibs = []
    if bld.env['static']:
        syslibs = ['m', 'z', 'gomp']
    else:
        syslibs = ['m', 'z']
    sources = bld.path.ant_glob('*.cc', excl=[])    
    for src in sources:
        target = str(src).replace('.cc', '')
        prog = bld( features = 'cxx cprogram', 
                    source = src,
                    target = target,
                    includes = ['.', '../library'],
                    lib = syslibs,
                    uselib = ['HARP'],
                    use = ['specex'],
                    vnum = wafutils.get_version_number() )                          
        prog.rpath  = [ bld.env['PREFIX'] + '/lib'] 
