# -*- mode: python -*-
# 

import wafutils

def build( bld ):
    sources = bld.path.ant_glob('*.cc', excl=[])    
    for src in sources:
        target = str(src).replace('.cc', '')
        prog = bld( features = 'cxx cprogram', 
                    source = src,
                    target = target,
                    includes = ['.', '../library'],
                    lib = ['m', 'z'],
                    uselib = ['HARP'],
                    use = ['specex'],
                    vnum = wafutils.get_version_number() )                          
        prog.rpath  = [ bld.env['PREFIX'] + '/lib'] 
