// This file is generated by autogen.sh- DO NOT EDIT!!
  
register_image ( "desi", image_desi_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_image ( "fits", image_fits_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_image ( "sim", image_sim_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_psf ( "gauss", psf_gauss_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_psf ( "gauss_sim", psf_gauss_sim_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_psf ( "gh", psf_gh_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_spec ( "desi", spec_desi_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_spec ( "desisim", spec_desisim_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_spec ( "fits", spec_fits_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_spec ( "sim", spec_sim_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_targets ( "desi", targets_desi_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_targets ( "fits", targets_fits_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

register_targets ( "sim", targets_sim_create, "9bf0dc72052a952422fe3a200cc7336e694d865d" );

  
